# Generated by Django 5.2.17 on 2026-09-20 19:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_employeedocument_archived_by'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('mac_address', models.CharField(blank=True, max_length=100)),
                ('connection_type', models.CharField(choices=[('NETWORK', 'Network'), ('ADMS', 'ADMS'), ('USB', 'USB'), ('FILE', 'File'), ('API', 'API'), ('OTHER', 'Other')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_devices', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDeviceEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_user_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='attendance.attendancedevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_device_mappings', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_user_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('DEVICE', 'Device'), ('WEB', 'Web'), ('MOBILE', 'Mobile'), ('API', 'API'), ('IMPORT', 'Import'), ('MANUAL', 'Manual')], max_length=20)),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('event_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='attendance.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='employee.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='organization.organization')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('INCOMPLETE', 'Incomplete'), ('OFF_DAY', 'Off Day'), ('HOLIDAY', 'Holiday'), ('ON_LEAVE', 'On Leave'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=20)),
                ('first_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_departure_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employee.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organization.organization')),
            ],
            options={
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('UNKNOWN_EMPLOYEE', 'Unknown Employee'), ('DUPLICATE_EVENT', 'Duplicate Event'), ('MISSING_CHECK_IN', 'Missing Check In'), ('MISSING_CHECK_OUT', 'Missing Check Out'), ('INVALID_EVENT', 'Invalid Event'), ('DEVICE_ERROR', 'Device Error'), ('MANUAL_REVIEW', 'Manual Review')], max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='attendance.attendanceevent')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_exceptions', to='employee.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_exceptions', to='organization.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_attendance_exceptions', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancedevice',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('organization', 'serial_number'), name='unique_attendance_device_serial_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='attendancedeviceemployee',
            constraint=models.UniqueConstraint(fields=('device', 'device_user_id'), name='unique_device_user_id_per_attendance_device'),
        ),
        migrations.AddConstraint(
            model_name='attendancedeviceemployee',
            constraint=models.UniqueConstraint(fields=('device', 'employee'), name='unique_employee_mapping_per_attendance_device'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_attendance_record_per_day'),
        ),
    ]
