# Generated by Django 5.2.17 on 2026-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='checkout_source',
            field=models.CharField(choices=[('NONE', 'None'), ('DEVICE', 'Device'), ('WEB', 'Web'), ('MOBILE', 'Mobile'), ('API', 'API'), ('MANUAL', 'Manual'), ('SYSTEM', 'System')], default='NONE', max_length=20),
        ),
    ]
