# Generated by Django 5.2.17 on 2026-09-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_checkout_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='source',
            field=models.CharField(choices=[('DEVICE', 'Device'), ('WEB', 'Web'), ('MOBILE', 'Mobile'), ('API', 'API'), ('IMPORT', 'Import'), ('MANUAL', 'Manual'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
