# Generated by Django 5.2.17 on 2026-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
