# Generated by Django 5.2.17 on 2026-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
    ]
