# Generated by Django 5.2.17 on 2026-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='automatic_attendance_checkout_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
