# Generated by Django 5.2.17 on 2026-08-23 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_per_year', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum_days_per_request', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('maximum_days_per_request', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('allow_half_day', models.BooleanField(default=False)),
                ('allow_carry_forward', models.BooleanField(default=False)),
                ('maximum_carry_forward_days', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='organization.organization')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leave.leavetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_leave_type_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'leave_type'), name='unique_leave_policy_per_type_and_organization'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('days_per_year__gte', 0)), name='leave_policy_days_per_year_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_days_per_request__gte', 0)), name='leave_policy_minimum_days_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_days_per_request__isnull', True), ('maximum_days_per_request__gte', 0), _connector='OR'), name='leave_policy_maximum_days_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_carry_forward_days__isnull', True), ('maximum_carry_forward_days__gte', 0), _connector='OR'), name='leave_policy_max_carry_non_negative'),
        ),
    ]
