# Generated by Django 5.2.17 on 2026-08-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_publicholiday_workschedule'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='organization',
            field=models.ForeignKey(default='77e58c90-ed17-4041-888a-2e1a0013ca05', on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='organization.organization'),
            preserve_default=False,
        ),
    ]
