# Generated by Django 5.2.17 on 2026-08-30 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeedocument_archived_by'),
        ('leave', '0005_leaverequest_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule_assignments', to='employee.employee')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='leave.workschedule')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
