# Generated by Django 5.2.17 on 2026-08-31 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeedocument_archived_by'),
        ('leave', '0006_employeeworkschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='prorate_for_new_hires',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_override', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to='employee.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_entitlements', to='leave.leavetype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_employee_leave_entitlement')],
            },
        ),
    ]
