# Generated by Django 5.2.17 on 2026-09-01 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leavepolicy_prorate_for_new_hires_leaveentitlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adjustment_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('reason', models.TextField()),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_balance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='leave.leavebalance')),
            ],
            options={
                'ordering': ['-adjusted_at'],
            },
        ),
    ]
