# Generated by Django 5.2.17 on 2026-09-01 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leavebalanceadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='accrual_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='accrual_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='ANNUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='accrual_start_month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='LeaveAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('accrued_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accruals', to='leave.leavebalance')),
            ],
            options={
                'ordering': ['-year', '-period_month'],
                'constraints': [models.UniqueConstraint(fields=('balance', 'year', 'period_month'), name='unique_leave_accrual_period')],
            },
        ),
    ]
