# Generated by Django 5.2.17 on 2026-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_leavepolicy_accrual_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='accrual_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='accrual_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='ANNUAL', max_length=20),
        ),
    ]
