# Generated by Django 5.2.17 on 2026-09-19 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeedocument_archived_by'),
        ('leave', '0010_leavebalance_accrual_enabled_and_more'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.PositiveIntegerField()),
                ('minimum_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('maximum_days', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='leave.leavetype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approval_rules', to='organization.organization')),
            ],
            options={
                'ordering': ['approval_level'],
                'constraints': [models.CheckConstraint(condition=models.Q(('approval_level__gte', 1)), name='leave_approval_rule_level_positive'), models.CheckConstraint(condition=models.Q(('minimum_days__gte', 0)), name='leave_approval_rule_min_days_non_negative'), models.CheckConstraint(condition=models.Q(('maximum_days__isnull', True), ('maximum_days__gte', 0), _connector='OR'), name='leave_approval_rule_max_days_non_negative'), models.UniqueConstraint(condition=models.Q(('leave_type__isnull', False)), fields=('organization', 'leave_type', 'approval_level'), name='unique_leave_approval_rule_specific_level'), models.UniqueConstraint(condition=models.Q(('leave_type__isnull', True)), fields=('organization', 'approval_level'), name='unique_leave_approval_rule_default_level')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_approval_steps', to='employee.employee')),
                ('approver_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='leave.leaverequest')),
            ],
            options={
                'ordering': ['approval_level'],
                'constraints': [models.UniqueConstraint(fields=('leave_request', 'approval_level'), name='unique_leave_approval_step_per_level')],
            },
        ),
    ]
