# Generated by Django 5.2.17 on 2026-09-23 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_leaveapprovalrule_leaveapprovalstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_period_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='leave.workschedule')),
            ],
            options={
                'ordering': ['day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('work_schedule', 'day_of_week'), name='unique_work_schedule_day')],
            },
        ),
    ]
